version: '3.8'

services:
  # Gmail Automation Backend
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=gmail_automation
      - MYSQL_PASSWORD=secure_password_123
      - MYSQL_DATABASE=gmail_automation
      - DB_POOL_SIZE=25
      - DB_MAX_OVERFLOW=100
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    networks:
      - gmail_automation

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: gmail_automation
      MYSQL_USER: gmail_automation
      MYSQL_PASSWORD: secure_password_123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_config:/etc/mysql/conf.d
    restart: unless-stopped
    command: >
      mysqld
      --max_connections=500
      --innodb_buffer_pool_size=1G
      --innodb_log_file_size=256M
      --query_cache_size=64M
    networks:
      - gmail_automation

  # Redis for Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - gmail_automation

  # Nginx (Optional - for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - gmail_automation

volumes:
  mysql_data:
  redis_data:

networks:
  gmail_automation:
    driver: bridge
